FROM apache/airflow:2.8.1-python3.10

USER root
RUN apt-get update && apt-get install -y \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    statsbombpy==1.18.0 \
    pandas==2.1.4 \
    numpy==1.26.3 \
    psycopg2-binary==2.9.9 \
    dbt-postgres==1.7.4 \
    scikit-learn==1.4.0 \
    xgboost==2.0.3 \
    scipy==1.12.0 \
    mplsoccer==1.2.4 \
    matplotlib==3.8.2 \
    weasyprint==60.2 \
    joblib==1.3.2 \
    requests==2.31.0
